project:
  type: website

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml


website:
  title: "quartodoc"
  page-navigation: true
  navbar:
    left:
      - file: get-started/overview.qmd
        text: Get Started
      - file: example.qmd
        text: Example
      - file: tutorials/
        text: Tutorials
      - href: api/
        text: Reference

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: proboundsviz

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - proboundsviz.create_probounds_table